export { default as Navbar } from './Navbar/Navbar';
export { default as Products } from './Products/Products';
export { default as Cart } from './Cart/Cart';
export { default as Checkout } from './CheckoutForm/Checkout/Checkout';
export { default as SlideShow } from './SlideShow/Slider';
export { default as Footer } from './Footer/Footer';
export { default as TopProducts } from './Products/Pages/TopProducts';
export { default as BottomProducts } from './Products/Pages/BottomProducts';
export { default as DetailProDuctPage } from './DetailProductPage/DetailProduct.jsx';